# Template Composition Example
# Demonstrates: Calling other templates, template_input, context isolation

name: composed_workflow
description: Build complex workflows by composing simpler templates
version: 1.0.0
author: MCP-CLI Team
tags: [composition, workflow, modular]

config:
  defaults:
    provider: anthropic
    model: claude-sonnet-4

# Note: This template assumes these other templates exist:
# - security_check.yaml
# - quality_check.yaml
# - performance_check.yaml

steps:
  # Step 1: Run security analysis (separate template)
  - name: run_security_check
    template: security_check
    template_input: "{{code}}"
    output: security_result
  
  # Step 2: Run quality analysis (separate template)
  - name: run_quality_check
    template: quality_check
    template_input: "{{code}}"
    output: quality_result
  
  # Step 3: Run performance analysis (separate template)
  - name: run_performance_check
    template: performance_check
    template_input: "{{code}}"
    output: performance_result
  
  # Step 4: Synthesize all results
  - name: create_comprehensive_report
    prompt: |
      Create a comprehensive code review from these specialized analyses:
      
      Security Analysis:
      {{security_result}}
      
      Quality Analysis:
      {{quality_result}}
      
      Performance Analysis:
      {{performance_result}}
      
      Format as:
      # Comprehensive Code Review
      
      ## Executive Summary
      [Overall assessment]
      
      ## Detailed Findings
      ### Security
      [Key security findings]
      
      ### Quality
      [Key quality findings]
      
      ### Performance
      [Key performance findings]
      
      ## Priority Recommendations
      [Top 5 actions to take]
      
      ## Next Steps
      [Recommended follow-up]
    output: final_report

# Benefits of template composition:
# 1. Reusability - Each check template can be used independently
# 2. Maintainability - Update one template, all compositions benefit
# 3. Context Isolation - Each template has clean variable scope
# 4. Token Efficiency - Only final results are passed, not full conversations
#
# Usage:
# mcp-cli --template composed_workflow --input-data '{"code": "..."}'

# Supporting templates needed (create these separately):

# config/templates/security_check.yaml:
# name: security_check
# steps:
#   - name: check
#     prompt: "Security analysis: {{stdin}}"
#
# config/templates/quality_check.yaml:
# name: quality_check  
# steps:
#   - name: check
#     prompt: "Quality analysis: {{stdin}}"
#
# config/templates/performance_check.yaml:
# name: performance_check
# steps:
#   - name: check
#     prompt: "Performance analysis: {{stdin}}"
